import streamlit as st

st.title("📖 About The Project")

st.markdown("""
## Malaria Symptom Triage Helper

The Malaria Symptom Triage Helper is a Machine Learning
application developed to assist in the early identification
of malaria cases and assess disease severity based on
patient symptoms, clinical measurements, and risk factors.

The system is intended as a decision-support tool and
does not replace professional medical diagnosis.
""")

st.header("Problem Statement")

st.write("""
Malaria remains one of the leading causes of illness and
death in many parts of the world, especially in
Sub-Saharan Africa.

Early diagnosis and proper severity assessment are
critical for reducing complications and improving
patient outcomes.

This project uses Machine Learning techniques to assist
healthcare workers in identifying malaria cases and
estimating disease severity.
""")

st.header("Project Objectives")

st.markdown("""
### Main Objectives

- Predict whether a patient has malaria.
- Assess malaria severity.
- Compare multiple machine learning models.
- Explain model decisions using Explainable AI.
- Provide triage recommendations.

### Business Value

- Faster screening.
- Better triage decisions.
- Support for healthcare workers.
- Improved patient outcomes.
""")

st.header("Dataset Information")

st.write("""
Dataset Size: 5,000 patient records

Features: Demographics, Symptoms, Clinical Measurements,
Risk Factors, Treatment Outcomes

Target Variables:

1. Diagnosis
   - Malaria
   - No Malaria

2. Severity
   - Uncomplicated
   - Moderate
   - Severe
""")

st.header("Machine Learning Pipeline")

st.markdown("""
1. Data Collection

2. Exploratory Data Analysis (EDA)

3. Data Preprocessing

4. Feature Engineering

5. Model Training

6. Model Evaluation

7. Hyperparameter Tuning

8. Explainable AI (SHAP & Feature Importance)

9. Deployment with Streamlit
""")

st.header("Models Evaluated")

st.table({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "KNN",
        "SVM"
    ]
})

st.header("Best Performing Model")

st.success("""
Random Forest achieved the best performance:

Accuracy: 99.4%

Precision: 99.1%

Recall: 100%

F1 Score: 99.57%

ROC-AUC: 99.94%
""")

st.header("Ethical Considerations")

st.warning("""
This application is intended for educational and
decision-support purposes only.

The predictions generated by the model should not
be considered a substitute for professional medical
diagnosis or treatment.

Healthcare professionals should always make final
clinical decisions.
""")

st.header("Project Author")

st.markdown("""
### Temidayo Samuel Abodunrin

AI / Machine Learning Engineer

Capstone Project:
Malaria Symptom Triage Helper

Technologies Used:

- Python
- Pandas
- NumPy
- Scikit-Learn
- SHAP
- Streamlit
- GitHub
""")

st.markdown("---")

st.caption(
    "Malaria Symptom Triage Helper • Machine Learning Capstone Project • 2026"
)